### ISSUE TITLE
QueryOptimizer ignores case sensitive userids

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-workflow#12]
I notice that the current implementation did not compare the userid case sensitive. 
The reason seems to be the method queryOptimier() which generates an SQL IN
Operator:

... where access807.value IN ('','http://Max-Mustermann.myopenid.com')

And the IN Operator did not compare strings in case sensetive mode.
In different the method load(String id) and the included method
isCallerReader() did compare the userid case sensitive.

This leads into a problem. For example a the call of findAllEntities() did
return a list of workitems whehre the readaccess compare was not case sensitive.
Next if the code calls the method load() this will be case sensitive. But now
the same workitem will not be returned.!

So in the moment it is very important that the user id is case sensitive.

I am not sure how to fix this issue? Maybe there is a change to change the
optimizeQuery() method and change the IN Operator to force a case sensitive compare.

**Comment by adimanm** [comment]
where can i download this software?
I want to install this project.

**Comment by rsoika** [comment]
For the Imixs-Workflow Engine, you can take a look at the 'getting started guide' here:
http://www.imixs.org/jee/get_started.html

There is also a deployment guide if you want to include the engine into you own JEE project: 
http://www.imixs.org/jee/deployment/overview.html

**Comment by rsoika** [comment]
obsolete, solved with version 4.0.0
