### ISSUE TITLE
Java 8 Compatibility (Scriptengine-Switch from Rhino to Nashorn)

### ISSUE THREAD

**Issue by autentagit** [imixs/imixs-workflow#124]
Using the RulePlugin in Java8 causes an Error (using wildfly 9.0.2 with Java 1.8.66):

[RulePlugin] error evaluating activity.get('keyaddwritefields') - ReferenceError: "importPackage" is not defined in <eval> at line number 1

Source-Code causing this error looks like this:

		// now try to pass the object to engine and convert it into a
		// ArryList....
		try {
			String jsCode = "importPackage(java.util);"
					+ "var _evaluateScriptParam = Arrays.asList(" + expression
					+ "); ";
			// pass a collection from javascript to java;
			engine.eval(jsCode);

The keyaddwritefields causing this were defined like this:

        <imixs:item name="keyaddwritefields" type="xs:string">
          <imixs:value><![CDATA[namprocessmanager]]></imixs:value>
          <imixs:value><![CDATA[namprocessteam]]></imixs:value>
          <imixs:value><![CDATA[namspacemanager]]></imixs:value>
          <imixs:value><![CDATA[namspaceteam]]></imixs:value>
        </imixs:item>

problem: Nashorn does not allow importPackages any more.

Switching back to Java 1.7 solved this problem, but this should be adressed sometime in the future.
This Problem is also described here: 
http://stackoverflow.com/questions/22502630/switching-from-rhino-to-nashorn and a migration guide is here: 
https://wiki.openjdk.java.net/display/Nashorn/Rhino+Migration+Guide

**Comment by rsoika** [comment]
Hi,
thanks a lot for your feedback.
Yes you are absolutely right. We know from this problem with Java8 and the usage of the script engine.
Your workarround with JDK 7 is the right guess. 

I try to fix this issue within release 3.6.0

**Comment by rsoika** [comment]
closed
