### ISSUE TITLE
Could Activiti  be  another imixs-workflow-engine  ?

### ISSUE THREAD

**Issue by yangboz** [imixs/imixs-workflow#172]
Could Activiti  be  another imixs-workflow-engine  ?
Open Source Activiti: http://activiti.org

**Comment by rsoika** [comment]
Activiti and Imixs both use BPMN but the engines follow different approaches. Imixs-Workflow follows a human-centric concept. Human-centric business process management supports human skills and activities by a task orientated workflow-engine. Most of the modelling concepts in Imixs-Workflow follow this idea. So I don't think you can mix these technologies.
The question is, what you want to achieve and which business requirements you have to fulfill? If you have to guide a user through a long running business process, Imixs-Workflow is a good solution.

**Comment by yangboz** [comment]
And Activiti has intergrated LDAP server,how about imixs-workflow-engine?

**Comment by rsoika** [comment]
Activiti has not integrated a LDAP server, but provides an adapter to connect to a LDAP server. 
Imixs-Workflow is based on the Java EE specification which means that the engine is independent from any database vendor or security concept. You can integrate any LDAP directory for authentication or any technology of your choice compatible with the 'Java Authentication and Authorization Service' (JAA) standard. This can be for example a database user directory, a directory server or also any newer token based authentication technology.
See details about security here: http://www.imixs.org/doc/deployment/security.html

An ldap adapter simmilar to the module you found on activity is the Imixs-Adapter LDAP project: https://github.com/imixs/imixs-adapters/tree/master/imixs-adapters-ldap-ejb

**Comment by yangboz** [comment]
OK,that's I wanted, Human-centeric BPM with LDAP server adapter,then Micro-Service with RESTful API, imixs did whole thing for current business requirement, great work! thanks, @rsoika
