### ISSUE TITLE
Callback methods for events

### ISSUE THREAD

**Issue by rangalo** [imixs/imixs-workflow#184]
I need a way to get some java (custom class) methods called on every event in my bpmn workflow. Ist this possible  ?  

Is a custom plugin the solution ?

**Comment by rsoika** [comment]
Yes you should implement a custom plugin class and add this plugin into your model. Then the plugin is called every time an Imixs BPMN event is processed. You can test the state of the event and workitem in the run() method. So you can decide if your plugin has something to do or exit immediately. 

Here is a simple example

````
@Override
	public int run(ItemCollection documentContext, ItemCollection event) {

		
		// Skip if plugin this processing a workitem without interesting data...
		if (!documentContext.hasItem("my_data_field") || documentContext.getItemValueString("my_data_field").isEmpty()) {) {
			// nothing to do....
			return Plugin.PLUGIN_OK;
		}

		// Skip if the event is not the one we are looking for....
		int eventID=event.getItemValueInteger("numActivityID") 
		if (eventID != 99) {
			// nothing to do....
			return Plugin.PLUGIN_OK;
		}

		// do the job....

		// update data
		documentContext.replaceItemValue("my_data_field","new data...");
		.....
		return Plugin.PLUGIN_OK;
	}````

**Comment by rsoika** [comment]
See also the PluginException to abort the processing of a workitem 
http://www.imixs.org/doc/engine/plugins/exception_handling.html

**Comment by rsoika** [comment]
closed
