### ISSUE TITLE
Can I use this software in my web server (used by a commercial web site)?

### ISSUE THREAD

**Issue by hrajeshkumar** [imixs/imixs-workflow#212]
Hi, 
    I am building a commercial web site which will provide a different set of services (job, content, training) to users. We charge them based on the service we provide. We would like to use imixs workflow engine on our server to automate some of our business processes. Is it legally fine to use this software in our server for our purpose?

Thanks in advance.

Regards,
Rajesh

**Comment by rsoika** [comment]
Yes of course, you can use Imixs-Workflow and there is no violation of the GPL in your main application. In the case you describe your application would probably be a separate work. And this is the typical usage of the Imixs-Workflow engine. See also [here](http://blog.imixs.org/gpl-imixs-workflow-affect-application/). Also if you are not distributing the software and the source code of your software you are not affected by the GPL or violating it. 

Please note that we will release the version 4.0.0 in a few days. This is a new Major release which brings a lot of performance improvements. It probably would make sense to you to start with 4.0, to avoid a later migration from 3.x. Version 4 is based on JDK 1.8.

===
Ralph

**Comment by hrajeshkumar** [comment]
Hi Ralph,
           Excellent! Thanks for your quick response!
Regards,
Rajesh
