### ISSUE TITLE
Not able to deploy imixs-jsf-example-master on Oracle Glassfish Server 3.1.2.2 

### ISSUE THREAD

**Issue by AbhijitRanjan** [imixs/imixs-workflow#243]
Hello,

I have followed the installation document () and was able to generate the .war file and Setup the glassfish server with JDBC Resource and Pool. Also added the security realm, but while deploying the implementation guide asks to select the .ear file where as I only have the .war

Can someone please help me through the next steps.

Thanks

**Comment by rsoika** [comment]
In your case just deploy the war file. 
I will fix this issue in the docu.
Please give us a feedback if deployment succeeds.

**Comment by rsoika** [comment]
Please note: the current version of imixs-workflow is based on JDK-8. So it is recommended that you use Glassfish 4.x or Payara Application server 4.x

**Comment by AbhijitRanjan** [comment]
I am using glassfish 3.1.2.2 as we have it for Oracle Adf deployments and
that's the oracle certified compitable version.

Please suggest which version of imixs should I use and if u could point me
to the relavant installation steps.

Thanks

**Comment by rsoika** [comment]
In this case try the JSF-Example 3.9.0 
https://github.com/imixs/imixs-jsf-example/releases/tag/imixs-jsf-example-3.9.0
This is the latest version where we do not force Java-8 and Java EE7
