### ISSUE TITLE
Issue deploying sample application on Payara

### ISSUE THREAD

**Issue by Fab64** [imixs/imixs-workflow#262]
I have followed the "GlassFish Deployment Guide" to setup the environment and I have built the sample application as described in section "The Imixs-JSF-Sample Application".

Once I upload the war file, I get the following error:

Error occurred during deployment: Exception while deploying the app [imixs-jsf-example-4.0.3] : The RunAs role "org.imixs.ACCESSLEVEL.MANAGERACCESS" is not mapped to a principal.. Please see server.log for more details.

What am I doing wrong?

**Comment by rsoika** [comment]
Hi,
the error message indicates that the realm 'imixsrealm' is missing or not configured accordingly (missing role mapping).
When you build the project with maven please note that you need to activate the maven glassfish4 profile:

    mvn clean install -pglassfish4

this would map the glassfish-web.xml and the correct web.xml file into the project. Have you checked if the glassfish-web.xml is available in your war file (located under /WEB-INF/glassfish-web.xml)

Also for deployment it is necessary, that a security realm named 'imixsrealm' is configured in glassfish  and that you have at least one user mapped to the group 'IMIXS-WORKFLOW-Manager'.

Which version of glassfish did you try? Glassfish4 is recommended. Payara is mostly better.

Let me know if this helps you to solve the problem. If not let me know so I can do some tests with the latest release. 

===
Ralph

**Comment by ArduinoManager** [comment]
Hi Ralph,

Thank you for your prompt answer. The problem was the glassfish4 profile. Please, note that the option is in upper case:

`mvn clean install -Pglassfish4`

You should also update the documentation section, because the profile is not mentioned there.

The same section contains another small error: once the application is deployed to glassfish it's reachable at this address:
`http://localhost:8080/imixs-jsf-example-4.0.3/`

Thank you again for your suppor.

Fab.

**Comment by rsoika** [comment]
Thanks for your feedback. Yes we need to update the glassfish install guide. I also want to remove the need of different profiles completely. The different deployment descriptors are a kind of legacy code from the beginnings of Java EE.

**Comment by rsoika** [comment]
ToDos, see: imixs/imixs-jsf-example/issues/11

**Comment by rsoika** [comment]
fixed

imixs-jsf-example 4.0.4 released

**Comment by aaj013** [comment]
I have tried 
> mvn clean install -Pglassfish4
But the reply is 
**The requested profile "glassfish4" could not be activated because it does not exist.
**

**Comment by rsoika** [comment]
hi,
the profile is no longer needed, so 

    mvn clean install

should be sufficient.
I also just removed the snapshot dependecy in the master tree. So please update you code base and try it once again.

**Comment by aaj013** [comment]
Ok i will try again
