### ISSUE TITLE
Adding Application Groups

### ISSUE THREAD

**Issue by OmoAmiroko** [imixs/imixs-workflow#272]
I have been trying to use Imixs Workflow in a J2EE  application and the experience is interesting. I have a challenge fetching workItems for user roles that are not defined in the realm configuration. I have many user roles (over 200) and I currently have users and roles managed within the application. Is there a way I can make the documentService make use of application roles that are not defined in the realm? I saw that the documentService reads applicationGroups which are loaded as ejb SessionContext data for the documentService, but since the documentService is stateless, it does not retain accesslist set in one instance.  
I wish to join the project and contribute to its development. I see it is a work in progress and I believe there are still many important features yet to be implemented, especially addition of custom imixs Workflow elements to the Eclipse modeler. 
Thank you.

**Comment by rsoika** [comment]
Yes - there are several ways to solve such problems. 

First of all, the roles assigned to the JAAS context (realm) are automatically verified by the workflow engine. This means if a process instance is assigned to a read- or write-access role named 'MY-ROLE', a user which is not in this role will be unable to read or modify the workitem. 
Regardless, you can also select the workitems by this read- and write restrictions.

```
(type:"workitem") AND ($readaccess:"MY-ROLE" OR $readaccess:"OHTER-ROLE")
                  AND ($writeaccess:"MY-ROLE" OR $writeaccess:"OHTER-ROLE")
```

You can extend this mechanism to your own application roles if you use a Intercepter. See the following example class:

```
 public class UserGroupInterceptor {
    @Resource
    SessionContext ejbCtx;

    @AroundInvoke
    public Object intercept(InvocationContext ctx) throws Exception {
       ctx.getContextData().put(DocumentService.USER_GROUP_LIST, "MyGroup");
       return ctx.proceed();
    }
 }
```

This class will automatically add the role 'MyGroup' to the user group context. This role/group is now equal to any JAAS role defined by a security realm. 
In the interceptor class you can validate your user using the Java EE sessionContext or any other business logic. We use this mechanism for example to resolve LDAP groups from an external directory. See here: https://github.com/imixs/imixs-adapters/blob/master/imixs-adapters-ldap-ejb/src/main/java/org/imixs/workflow/ldap/LDAPGroupInterceptor.java

But roles can also be used independent form the read/write access. In this case, you can define the ownership by the BPMN model. The roles/groups will be added into the attribute 'namowner'. This is independent from any read- or write restriction:

`(type:"workitem") AND (namonwer:"MY-ROLE")`

If you want to assign your roles to a custom workitem attribute (e.g. 'businessroles'), you can simply add this attribute to the index by adding the name into the imixs.properties file:

`lucence.indexFieldListNoAnalyze=businessroles`

then you can select workitems by this field:

`(type:"workitem") AND (businessroles:"MY-ROLE")`

But I think the Iterceptor class is what you are searching for. 
I hope this helps. You can share your model so we can discuss the problem on an example. 

===
Ralplh

**Comment by OmoAmiroko** [comment]
Thanks a lot for the detailed and quick response. I believe the interceptor class will solve my problem and I will go ahead and implement it. I will let you know how it goes.... 👍

**Comment by OmoAmiroko** [comment]
Hi Ralph. I have implemented the interceptor class and it works as expected. However, I am still having a small challenge, which I know a work-around, but let me explain my model perhaps you will be able to suggest a better idea. 
I have a workflows that will be acted upon by different people within an organization. These people (users)are to be authenticated against the active directory. However, every user is assigned a position (role) and these are maintained within the application using a table that maps roles to users. A user, when acting on a work item, could do so as an individual or as the occupier of a role. For example, when creating a workItem as an individual, the creator is set to the userId, but when creating as a role e.g Manager HR, the creator is set as the roleId.
This is all fine, until when a user logs in and I attempt to retrieve work items he created. The ones created as an individual are retrieved because the documentService uses the principal name, which is the userId, for retrieval. But it doesn't not fetch the workItems created as a role, which is why I needed the interceptor. 
My (small)  challenge now is that documentService checks against the field namcreator, whereas I set the creator using the field $creator. I know I can correct this by setting both $creator and namcreator, but the use of the interceptor is not an elegant solution. Is it impossible to set the user roles once per session, instead of everything the documentService ejb is invoked? Is there a better way to achieve this? 
Finally, I am storing all the users/roles that have acted on a workItem in a field called _trail, which is a list of Strings. For a user, I want to fetch all the workItems he has worked on, whether he created them or not. So currently, what I do is to add all the userIds and roleIds in the _trail to the $readaccess of a workItem so that I can fetch those workItems using a searchTerm like "_trail:userId" . Do you have a better suggestion?

**Comment by rsoika** [comment]
Hi,
I am not sure if I understand your problem completely. 
But don't mix roles and userIDs. The UserID (caller principal name) is an important core concept for human-centric workflow. A user creating a new workitem is the creator ($creator), independently of its current or future roles within an organisation. And there can only be one creator for each process instance. A user last processed a workitem is stored in the field $editor. Do not manipulate those fields. 
See also: http://www.imixs.org/doc/quickstart/workitem.html

If you want to assign the workitem also to one or different roles you can do this by the BPMN model. Just  assign specific roles directly to the ACL for writeaccess or the owner flag. This will allow you to display a similar task list to all users currently assigned to a specific role. Use the methods getWorkListByAuthor() or getWorkListByOwner(). Your Interceptor will do the role management. This works also if the roles will change for users in the future. 

But do not manipulate the $creator or $editor field by your application. 
In general it is recommended to work more with userIds and less with roles. Imaging a approval workflow, where several managers have to approve a request. In this case it is important to know the userIds and not the manager role. The later one will change in the future but this will not mean that ab already approved workitem was approved by the new managers. In this scenario I would create a field "namApprovers" and add all the current manager userids. The field 'namApprovers' works as a Snapshot from the point of time where the request was ready for approvement. The 'manager-role' can be used to resolve the list of managers but should not be assigned to the approver mechanism. 

Your idear with the _trail field is totally fine. If you make sure, that in your BPMN model the _trail field is always ticked in the ACL $readaccess section, a user can only see workitems he was involved before. This is very usefull for confidential workflows. The roles can be added to the ACL by the model, but should not be stored in the _tail field. 

===
Ralph

**Comment by OmoAmiroko** [comment]
Thanks a lot for your comments and suggestions. I agree with you on the need to always maintain the $creator and not modify it. I will adjust on that.  

I can't assign workItems to roles in the BPMN Model because the role a workItem will be assigned to will not be known until runtime. You may find that strange but that is the way my model is designed currently. But I am assigning it in code, and I am fine with that. 

Unfortunately, the organizational processes work with roles more than users occupying those roles. A workitem will be assigned to the role because the user occupying the role can change and the new user in that role should have access to the workItem. For example, if a workItem is supposed to be approved by Manager HR, I will add the role mgr_hr to the $writeaccess. This will enable anybody with this role to work on the item. But this brings a small challenge. The _trail field used for capturing actor history stores the role, because if the user is changed, the new user should be able to see the workItems that the previous user acted on. I also need to capture the users  that acted  on a workItem, not just the roles, for audit and accountability reasons. The $editor field is not sufficient because it only captures the last editor. In my process, workItems can go round in a loop such that it comes to the same role twice. If the user has been changed between the first and the second assignment, I should be able to capture the old and new users that acted on it. My current idea is to have two trails,  one for users (which will store the caller principal names) and one for roles (which will store roleIds) . The one for users will be used for accountability while the one for roles will be used to determine accessibility. And I will need to capture timestamps too, in order to know when a user acted on a workItem, since it is possible for the same user to act on the same workItem two or more times in its lifecycle. The capturing of timestamps is a bit challenging and I haven't developed an idea on implementing it yet. Do you have any suggestion on that? 

Note: I can send my model to you privately if you wish to see it.

**Comment by rsoika** [comment]
Two thoughts on your problem description:

**1. Assigning Workitems to roles:**
To assign your workitem to the roles, you can go the following way:

1. Write a custom plug-in class which computes the necessary roles (maybe this is already done by your interceptor class).
2. The Plug-in class should store the result into a custom field (e.g. _businessRoles)
3. In your BPMN model create a "Actor Property" like "Business Roles | _businessRoles"
4. In the ACL of your BPMN tasks you can now tick the Read-, Write- and Owner to this "Business Roles" as needed from your business process perspective. 

As a result, the Imixs-Workflow will automatically add the roles to the read/write/owner properties of your workitems. This is done by the plugin classess

- _org.imixs.workflow.engine.plugins.AccessPlugin_ 
- _org.imixs.workflow.engine.plugins.OwnerPlugin_ 

Add these plug-ins to your model. 

In your Workflow Suite Imixs-Office-Workflow we do exactly this with the 'org.imixs.marty.plugins.TeamPlugin'. This plugin computes the responsible actors by internal business logic and stores the result into fields like '_namTeam_', '_namManager_' and so on.. These fields are used in the BPMN model to grant the access and define the ownership. 

**2. Audit your Workflow**
To audit the history of a workitem you can just use the Plug-in class 

- _org.imixs.workflow.engine.plugins.HistoryPlugin_

In the BPMN Model you can add a suitable audit entry to each event. See the following examples:

`Request approved by <itemValue>$editor</itemValue>`

or 

`Request finished by <itemValue>$editor</itemValue> and forwareded to <itemValue>namowner</itemValue>`

The HistoryPlugin generates a consistently audit log for each workitem automatically. The log includes the userid and the the timestamp. The data is stored into the field txtworkflowhistory. 

Another interesting field is probably the field 'txtworkflowactivitylog' controlled by the WorkflowKernel. Take a look at it. Maybe we can extend the entries in this field with the $editor. So an entry would look like this:

```
2017-06-12T18:57:22.358|longterm_commitment-1.0|5000.10|5000|anna
2017-06-12T19:05:16.760|longterm_commitment-1.0|5000.20|5000|manfred
```


Independent form this feature you can and should control your two _trail fields. That's no bad idea. 
Maybe this would be also a good idea for a new workflow extension. Maybe we can develop a standard plug-in which adds new $editors to a new field $editor_history. Or we can add this feature into the WorkflowKernel.

**Comment by OmoAmiroko** [comment]
Both ideas you suggested look very promising and I will explore implementing them according to my needs. Thanks a lot. 

I mentioned I will like to join the project as a contributor. What is the procedure for doing that?

**Comment by rsoika** [comment]
**You are welcome to join the project!** 
As a GitHub member you can already contribute to the imixs-workflow project.
Just create a pull request from a fork of the project you created before.
Once a pull request is opened, we can discuss and review the potential changes and add follow-up commits before the changes are merged into the master repository.

After initializing a pull request, you'll see a review page that shows a high-level overview of the changes between your branch (the compare branch) and the main repository's. You can add a summary of the proposed changes and we can review the changes made by your commits

See also here: https://help.github.com/articles/creating-a-pull-request/
