### ISSUE TITLE
GF 4 error: The lifecycle method [initIndexProperties] must not throw a checked exception

### ISSUE THREAD

**Issue by anap12** [imixs/imixs-workflow#279]
Hello,

I am getting the following error while trying to deploy an application with imix 2 into GF 4:

Exception Occurred :Error occurred during deployment: Exception while deploying the app [zensi-report-ear-3.0.0] : The lifecycle method [initIndex] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PostConstruct()] on annotated element [void org.imixs.workflow.jee.ejb.ModelServiceBean.initIndex() throws java.lang.Exception] of type [METHOD]. 

Deploying the application into GF 2 works just fine.
Do you have any idea for an workaround?

Thank you and kind regards,
Ana

**Comment by rsoika** [comment]
I think you need to take care about the glassfish specific deployment descriptors. The deployment strategies changes since Java EE 5.

**Comment by anap12** [comment]
Thank you for the response.

I did some extra changes and now I am facing this:

Caused by: com.sun.proxy.$Proxy345 cannot be cast to javax.annotation.security.DeclareRoles. Related annotation information: annotation [@javax.annotation.security.DeclareRoles(value=[org.imixs.ACCESSLEVEL.NOACCESS, org.imixs.ACCESSLEVEL.READERACCESS, org.imixs.ACCESSLEVEL.AUTHORACCESS, org.imixs.ACCESSLEVEL.EDITORACCESS, org.imixs.ACCESSLEVEL.MANAGERACCESS])] on annotated element [class org.imixs.workflow.jee.ejb.ReportServiceBean] of type [TYPE]

	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:375)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:383)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.processAnnotations(AnnotationProcessorImpl.java:291)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:196)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:135)
	at com.sun.enterprise.deployment.archivist.Archivist.processAnnotations(Archivist.java:627)
	at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:463)
	... 77 more

**Comment by rsoika** [comment]
have you take care about the system setting

`com.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager=true`

This maybe an issue....
But at the end it is just guessing, because this is too less information.

**Comment by anap12** [comment]
I guess it is hard to see where the problem is, I am searching for it for a long time :)
But I am not giving up and I am sure I will find the issue and share the results here.

I tried your suggestion and I still do not have a success result.
Today someone suggested me to use from the deployment console the 'Compatibility' check
![image](https://user-images.githubusercontent.com/29570382/27435535-21fbae20-5765-11e7-8cc4-faf7ff9f5086.png)

I am getting again:
The lifecycle method [initIndexProperties] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PostConstruct()] on annotated element [private void org.imixs.workflow.jee.ejb.WorkflowServiceBean.initIndexProperties() throws java.lang.Exception] of type [METHOD]

The lifecycle method [initIndexProperties] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PostConstruct()] on annotated element [private void org.imixs.workflow.jee.ejb.WorkflowServiceBean.initIndexProperties() throws java.lang.Exception] of type [METHOD]

My first feeling is that if i rewrite the classes WorkflowServiceBean and ModelServiceBean to not throw Exception maybe my deploy will work.

Looks like the same issue in here: https://github.com/spring-projects/spring-boot/issues/868 

What do you think? Can I still find the imixs 2 project and download the sources?

Thank you.

**Comment by rsoika** [comment]
yes - you can find the sources in the maven central repository:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22imixs-workflow-api%22

But it's a stony road. Possible, it may be better to migrate to the newer versions 3. x or 4. x.

**Comment by anap12** [comment]
Hi,

Just an update. I  managed to deploy the application with success

My changes are:
- modify the 2 classes throwing the exception in the PostConstruct methods in imixs-jee-impl.2.1.4

- modify the web.xml to this:
<servlet>
    <servlet-name>Jersey Web Application</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class> 
    <init-param>
        <param-name>jersey.config.server.provider.packages</param-name>
        <param-value>org.imixs.workflow.jee.rest.jaxrs</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
</servlet>
<servlet-mapping>
    <servlet-name>Jersey Web Application</servlet-name>
    <url-pattern>/rest/*</url-pattern>
</servlet-mapping>

- modify the jersey to 1.13
 <dependency>
      <groupId>com.sun.jersey</groupId>
      <artifactId>jersey-servlet</artifactId>
      <version>1.13</version>
 </dependency>
