### ISSUE TITLE
DocumentService add count methods

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-workflow#284]
Add the missing implementation of count methods:

- int count(String query)
- int countPages(String query, int pageSize

```
public int countPages(String query, int pageSize) throws QueryException {
		double pages = 1;
		double count = count(query);
		if (count > 0) {
			pages = Math.ceil(count / pageSize);
		}
		return ((int) pages);
	}
```

The count method need to ask lucene for the result without loading the data into memory

**Comment by chrisw14** [comment]
Hi Ralph,
why do you set the pageIndex to 0 in doLoadPrev() ?
See: https://github.com/imixs/imixs-workflow/blob/88f510b782085edf2f74a24c4e9a61cac409761d/imixs-workflow-faces/src/main/java/org/imixs/workflow/faces/workitem/ViewController.java#L226

Greets
Chris

**Comment by chrisw14** [comment]
The end of a list is reached too when a page can show all workitems.
It should be: `endOfList = (workitems.size() <= pageSize);`
in https://github.com/imixs/imixs-workflow/blob/88f510b782085edf2f74a24c4e9a61cac409761d/imixs-workflow-faces/src/main/java/org/imixs/workflow/faces/workitem/ViewController.java#L276

**Comment by rsoika** [comment]
In both cases your are right!
I surprised I didn't stumble over it...

I added a new bug: #287

**Comment by chrisw14** [comment]
Hi Ralph,
how can I get the number of entries of a document (not the count of entries of the current page) when using a searchQuery AND
`setWorkitems(workflowService.getWorkListByOwner(...))` from ViewController.

`getWorkitems()` returns only the entries of the current page and the value of 
`workflowService.getWorkListByOwner(...).size()
`wouldn't consider the searchQuery :-(

Maybe I missed something?

**Comment by rsoika** [comment]
The result-set of a search/query is always a java.util.List. So the size() returns the count of entries in the result-set. It has nothing to do with the Lucene index. 
To get the absolute count of entries you must use the method '_documentService.count()_'

The _getWorklist_... methods of the WorkflowService did not support corresponding count methods. So you must write these method calls by your self. 

Even if you don't like to hear it, I don't recommend putting too much energy into the display of the maximum possible hits. The count method is not for free - it is cpu and memory consuming.
If you have a lot of users and huge amount of workitems, it is important to avoid searching through the hole data store to keep your application fast and responsive.
