### ISSUE TITLE
ViewController - compute 'end-of-page' and doLoadPrev()

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-workflow#287]
there are two bugs in the current implementation.
1. The pageIndex should not be set to 0 in doLoadPrev() 
2. The end of a list is reached too when a page can show all workitems. It should be:
 `endOfList = (workitems.size() <= pageSize);`

See discussion here https://github.com/imixs/imixs-workflow/issues/284#issuecomment-318834910

**Comment by chrisw14** [comment]
As I can see now, `workitems.size()` is only the number of workitems of the current page.
We need here the count()-method of DocumentService to compare if there are more pages or not.

**Comment by rsoika** [comment]
your are right - we need to see how many entries exits

**Comment by rsoika** [comment]
I tested it with the JSF-Sample-Application. It looks fine now for me.
Thanks for your help

**Comment by chrisw14** [comment]
Hi Ralph,
did you upload a new snapshot with this bugfix?
Cheers
Chris

**Comment by rsoika** [comment]
I think so. To be sure, I just uploaded it once again.
