### ISSUE TITLE
Change processId without activityId?

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#292]
Hi Ralph,

can you please tell me if it's possible to change the processId of a workitem without an event / activityId?
This would be interesting to cancel a workitem in every process step without adding this event to all workflow tasks. It would be great too if an admin could set back the workflow task from every process step to another which was before the current step.
Is it possible to modify the processId without the activityId of the event?

Thank you.
Chris

**Comment by rsoika** [comment]
Hi Chris,
changing the processid of a workitem is not recommended. Every transition into another state (task) should be performed by the method
`
workitem=workflowService.processWorkItem(workitem);
`
Only in this way your application can guarantee the consistence of the workitem lifecycle. 
If you modify the attribute $processid and then call the method process() the workflowManager will throw a exception. So you should provide a cancel event in any situation your business process allows to terminate the process. 
See also the concept of [LinkEvents](http://www.imixs.org/doc/modelling/howto.html)  to avoid to get too complex BPMN diagrams. 

You could of course change the attribute "$processid" using the documentService.save(workItem) method. But it is absolutely not recommended to do anything like that.
The reason is, as I said, that you take away the control of the process from the workflow engine. 
So never never do this! Even if it seems tempting.

===
Ralph

**Comment by chrisw14** [comment]
Thank you Ralph, I will have a look at the LinkEvents.
Question solved ;-)

**Comment by chrisw14** [comment]
Now I Wohle have a simular question to this topic:
How can I implement that someone who triggers an event has to give reasons in a Dialog for his decision after he clicks the event button?
Can I put Parameters for this in a field of a event in the Model?

**Comment by chrisw14** [comment]
Now I would have a simular question to this topic:
How can I implement that someone who triggers an event has to give reasons in a Dialog for his decision after he clicks the event button?
Can I put Parameters for this in a field of a event in the Model?

**Comment by rsoika** [comment]
I am not sure if I understand your question correctly. 
If, for example, you want to force the user to give a comment before he approves a workitem you can do this with a Business Rule.
http://www.imixs.org/doc/engine/plugins/ruleplugin.html

For example:

```
var result={};
 if (!workitem.txtcomment  || workitem.txtcomment[0]=='') {
    result.isValid=false;
    result.errorMessage='Please enter a comment when rejecting the request!';
 }
```

This will cancel the processing phase with a PluginException holding the error message. So you can display this message in your frontend.

**Comment by chrisw14** [comment]
Hi Ralph,
the Rule Plugin works fine, thank you.

Is there a documentation about the condition expressions of sequence flows? Didn't find out how to define a condition language, how the condition should look like or how can I define a data type.

And do you have an idea what's the easiest why to add the id of the next process to the txtworkflowhistory? At the moment I do it manually in the history message of the event. But when using conditions I can't know it at this point.

Thank you.
Chris

**Comment by rsoika** [comment]
Condition expressions in sequence flows are not supported by Imixs-BPMN. Just use the Business Rules evaluated by the Rule Plugin.
http://www.imixs.org/doc/engine/plugins/ruleplugin.html

To solve your problem with the 'next process id' you can add an additional event into the flow behind your condition which is only responsible for the new history entry. 

The 'new processid' is computed by the WorkflowKernel. So you have no direct access during the processing phase. The comment in the WorkflowController was a typo. 

A plugin can 'guess' the new process ID with the method 'getNextTask' returnin the next Task Element. But a plugin class can not be aware when and if the processing ends. So this is just a guess.

But why did you need the new process id in a history entry. This is a technical information. The history entry should be used to document the processing flow from a user perspective like:

    submitted by ....
    approved from ....
    forwarded to....

**Comment by chrisw14** [comment]
May I ask why there is no support for Condition expressions in sequence flows? I think it would be more clear in the bpmn model with labeled arrows and so on than the Rule Plugin.

> To solve your problem with the 'next process id' you can add an additional event into the flow behind your condition which is only responsible for the new history entry.

Okay, this would be possible but I need this every time so it would be good if I can solve this programmatically. But the problem is that the user doesn't have write permissions after executing the process method.

> A plugin can 'guess' the new process ID with the method 'getNextTask' returnin the next Task Element. But a plugin class can not be aware when and if the processing ends. So this is just a guess.

But this can't consider the conditional flow, or can it?

> But why did you need the new process id in a history entry.

I want to give the user an overview of the following tasks, considering his inputs. E.g. when he disables a checkbox a task can be skipped and the user should see this 'live' before he submits the form.
I solved this with a 'chain' of linked items in the history.

> `forwarded to....`

But this is what I need: To know to which task (or editors) the workitem is forwarded before and after the form is submitted.

**Comment by rsoika** [comment]
Can you upload a example BPMN model with the Condition expressions in sequence flows so we can discuss this based on an example?

**Comment by chrisw14** [comment]
At the moment I haven't a bpmn model with conditions in sequence flows. I saw it only on the imixs homepage and thought that these conditions are sequence flow conditions? Or how does these conditions work?
http://www.imixs.org/doc/images/modelling/example_06.png

**Comment by chrisw14** [comment]
> A plugin can 'guess' the new process ID with the method 'getNextTask' returnin the next Task Element. But a plugin class can not be aware when and if the processing ends. So this is just a guess.

This only returns the task of a set "numNextProcessID" which isn't set in my model or returns the current task. And of course "numNextProcessID" can't be a static value when using conditions.

https://github.com/imixs/imixs-workflow/blob/cf1c8b20d854418a70471c35537f7170bc50aa8b/imixs-workflow-engine/src/main/java/org/imixs/workflow/engine/plugins/AbstractPlugin.java#L493-L511

**Comment by rsoika** [comment]
Ok - the image from the homepage you reference is just an example. The business logic is in the business rule of the 'accept' event. The text in the sequence flows is just for illustration. Note: a BPMN model is always also a visual description of a business process. 
But the example is somewhat insufficient, because the next task is unclear in this diagram.

**Comment by rsoika** [comment]
From the modelling aspects, I guess you think about something like this:

![bpmn_conditional_sequence_flows](https://user-images.githubusercontent.com/1339124/30232150-9ba5ee72-94ee-11e7-85f5-684de11de747.png)

The conditions are added to the gateway element. This may be possible to implement. 
But we need to think about it....

**Comment by rsoika** [comment]
....but as longer I think about this, this solution would not work at the end. The Event is the main trigger for the Imixs-Workflow engine. The event is necessary to have a defined processing flow. So the model must look like this:

![bpmn_conditional_sequence_flows2](https://user-images.githubusercontent.com/1339124/30232382-02b7146e-94f0-11e7-8972-42395ce9c37a.png)

Only with this model style you have the control over the processing flow. And the additional events allow you to define the individual history entries for each condition. There is a lot of additional stuff to be modeled in a event (e.g. email notifications, ACL, result items, ...). So without these events you run in exactly the problem you described here. 
Now I don't think that it make sense to put parts of a business rule into a gateway.  This makes the model inaccurate at the end.

**Comment by chrisw14** [comment]
> ![](https://user-images.githubusercontent.com/1339124/30232150-9ba5ee72-94ee-11e7-85f5-684de11de747.png)

Yes that's what I would like to have. The business rule should be at the point of the decision and that's the gateway in my opinion. A gateway has already fields for conditions - why don't we use them instead of adding a plugin?
This way would be compatible to 'normal' bpmn diagrams like this:
https://camunda.org/assets/img/examples/invoice.png

> The event is necessary to have a defined processing flow. 
The event has a defined processing flow because there is only one way to proceed. In this example going to the gateway which can tell you what the next event or task is.

For me, the yellow events are only the action buttons the user can click. So the <100 and >=100 events doesn't make the process understandable in an easy way. The logic of these buttons could handle the workflow engine by adding a "incoming history log" of task 2 or 3 to to the workflow history. This could be the "forwarded to ..." log.

Of course your solution will work too but then the model implements logic of the workflow engine and the model is not understandable in a easy way I think.

And the other thing to compute the next process task should be possible with executing the existing process method but without changing any values of the current workitem. Maybe the easiest way is to make a deep copy of the workitem, processing this, see what the value of `$processid` is and remove the deep copy again?

**Comment by rsoika** [comment]
I have added a new issue (#299) to track this idea. I am not yet really convinced that it this will simplify the models at all. But let us continue the discussion and implementation here:
#299

**Comment by chrisw14** [comment]
> And the other thing to compute the next process task should be possible with executing the existing process method but without changing any values of the current workitem. Maybe the easiest way is to make a deep copy of the workitem, processing this, see what the value of `$processid` is and remove the deep copy again?

Hi Ralph, 
do you have an idea of an easier solution to compute the next process ids without creating a deep copy of the workitem, processing it, getting the result and deleting the cloned workitem? The process step needs much performance but on the other hand I need it because it checks out the model what the next process will be...

**Comment by rsoika** [comment]
Hi Chris,
I expected this kind of question ;-)

It is not easy to answer such a question because a event can be followed by another event and events can change the flow depending on rules (as you know).
But maybe the method 'getNextTask' of the class  

     org.imixs.workflow.engine.plugins.AbstractPlugin

will work for you? We use this method to compute the 'status icon' and the 'input form'

See the class 

    org.imixs.workflow.engine.plugins.ApplicationPlugin

But if you have conditional events (as I expect) this method will not work if you did not have follow up events at the outcome of the gateway. I expect you have. Again it would be easier to help if you share a screen of your model and we can discuss it on this example......

**Comment by rsoika** [comment]
I have been thinking about the problem once again and I think that there are two solutions:

- The first one is to simulate the process flow with an empty WorkflowKernel. So you can see the outcome without any database interaction.  I will provide a SimulationService bean for this 
 
- The second one is to use the new [PluginObserver Pattern](http://www.imixs.org/doc/engine/plugins/index.html).  This allows a plugin to be called back 'afterProcessing'. Maybe this is what you search.

But just to give you a hint how complex that problem can be: imagine you have a plugin fetching product data from a ERP system. And in addition you have conditional events evaluating the price of the fetched product. So simulation means to simulate also business logic from plugins. In such a case the PluginObserver Pattern could be the best solution. But I will provide the SimulationService with a method to add plugins to be called during the simulation. So this can be a interesting solution.....

**Comment by chrisw14** [comment]
Hi Ralph,
thanks for your interesting input.
I know the getNextTask-method but if you already  noticed it doesn't support the conditions. So it won't work for me.
But the SimulationService and the PluginObserver are great ideas. Thank you, I will have a look at it.

That's my model at the moment:
![model](https://user-images.githubusercontent.com/29482633/30478207-66842a52-9a10-11e7-82f1-7ba72d64aab6.png)

Cheers
Chris

**Comment by rsoika** [comment]
The new SimulationService will be helpful to answer this kind of question. 
You can simulate the processing flow without calling any plugin or persisting data into the database. 
See the example at: http://www.imixs.org/doc/testing.html

**Comment by chrisw14** [comment]
I tried the SimulationService without plugins and got a NullPointerException:

```
19:20:37,581 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-10) java.lang.NullPointerException
	at org.imixs.workflow.WorkflowKernel.loadEvent(WorkflowKernel.java:836)
	at org.imixs.workflow.WorkflowKernel.process(WorkflowKernel.java:277)
	at org.imixs.workflow.engine.SimulationService.processWorkItem(SimulationService.java:139)
```

Is this NullPointerException caused by the missing plugins?
Is it possible to get the list of the plugins from the model?
And can you please tell me how I can get the source attachment to the SNAPSHOT-jars?

Thank you!!

**Comment by rsoika** [comment]
You can get the plugins from the definition object:

    List<String> vPlugins = (List<String>) model.getDefinition().getItemValue("txtPlugins");

What did you mean with "_source attachment to the SNAPSHOT-jars?_"

You must clone the git repo to get the latest sources. Snapshot releases are provided in unsteady intervals.

**Comment by chrisw14** [comment]
> What did you mean with "source attachment to the SNAPSHOT-jars?"

Eclipse asks me for sources because I'm only downloading the snapshots with maven:
![sourceattachment](https://user-images.githubusercontent.com/29482633/30510759-4b569778-9aca-11e7-9370-3bb5607cafa9.png)
Can maven download them too?

**Comment by rsoika** [comment]
no, the imixs-workflow snapshot releases did not contain sources or javadoc files. 
So the only way to get sources is to clone the master branch from github. 

1. Copy the Git Location: https://github.com/imixs/imixs-workflow.git
2. Start the Import with: Import->Git->Project from Git->clone URI

**Comment by chrisw14** [comment]
But I don’t want to clone the master branch but only downloading the snapshots with source files, javadocs, …. For some days I could read the javadocs in eclipse too without downloading the master branch. Maybe it was a release and no snapshot?

**Comment by rsoika** [comment]
yes realeases are bundled with sources, snapshots are not. Than you must wait for the release of version 4.2.0
