### ISSUE TITLE
REST-Service - ModelService computes wrong download link for bpmn file

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#293]
Hi Ralph,
some questions about the REST-API (http://localhost:8080/workflow/rest-service/):

1. When I access http://localhost:8080/workflow/rest-service/model/ and click on a model I got to http://localhost:8080/workflow/rest-service/model/model/1.0.0/groups/Ticket which is wrong because of the double "model/model/". I think it's a small bug.

2. There is no selection on http://localhost:8080/workflow/rest-service/
It would be nice if you can walk trough the rest api.

3. How can I have access to all attributes of a model?
I would like to get the value of the documentation of the model file, called "Documentation_2" in the bpmn file. Is this possible?
`#{model.getDefinition().getItemValueString('Documentation_2')} does not work for me.`

Thank you.
Chris

**Comment by rsoika** [comment]
Hi Chris,

1. - yes this would be wrong. The access URL should be
 `  /model/1.0.1/groups/Ticket`
I verified this in the [Imixs-JSF-Sample application](https://github.com/imixs/imixs-jsf-example). And I can not see the behavior with the double  /model/model/
Which version of imixs-workflow are your running?

2. - yes this would really be helpful. But we have still no such api :-/
 
3. - the attribute 'documentation' from the definition is not exported I think. But check the attribute 'rtfdescription'. This attribute is part of Task and Event elements

**Comment by chrisw14** [comment]
1. I'm using the version 4.1.5-SNAPSHOT
The href of the hyperlink is: "./model/"
This means: http://localhost:8080/workflow/rest-service/model works fine, http://localhost:8080/workflow/rest-service/model/ doesn't work.
2. Okay.
3. This works. Thanks.

**Comment by rsoika** [comment]
That's interesting. We need to investigate into this bug

**Comment by rsoika** [comment]
We need to change the HTML view of the model service: 

_The href of the hyperlink is: "./model/"
This means: http://localhost:8080/workflow/rest-service/model works fine, http://localhost:8080/workflow/rest-service/model/ doesn't work._

**Comment by chrisw14** [comment]
Hi Ralph,
this works fine, thank you!
Can we use the rootContext at the following line too?
https://github.com/imixs/imixs-workflow/blob/34657f44434319dfeeaa27361a8e5157ddefa999/imixs-workflow-jax-rs/src/main/java/org/imixs/workflow/jaxrs/ModelRestService.java#L186

Cheers
Chris

**Comment by rsoika** [comment]
yes you are right - I will fix it. And we will release the version 4.1.5 today.
