### ISSUE TITLE
Conditional Events

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-workflow#299]
In order to avoid the fact that behind each gateway output an event must be defined, ' conditional events ' will be introduced in the future. 

## Problem

To compute the next Task in a processing life cycle the WorkflowKernel expects either an attribute 'numnextprocessid' or the attributes 'keyFollowUp=1' and  'numNextActivityID' pointing to another Event to be processed next.
This behavior makes it necessary that an Event unambiguous points to only one Task or Event. 
As a result _conditional gateways_ could not be modeled without additional Events at the output of the gateway. 

## Solution

The idea is to support Models like this one:

![bpmn_conditional_sequence_flows](https://user-images.githubusercontent.com/1339124/30239210-8fd1df16-9557-11e7-80f4-73b8e2de8671.png)

In this model the output of the Event is a Gateway defining Flow-Conditions. 
The Imixs-Workflow Engine should be aware of this Eventtype (which can be called '_conditional event_') and evaluate the conditions during processing to determine the next output Task or Event. 

## Implementation:

Currently I expect that the BPMN Parser is throwing an exception for the model example above, because the output is not unique. 
We can extend the parser in a way where we analyse if a _Conditional-Gateway_ is the next output. If so, the conditions can be added into the Event which now becomes a 'Conditional-Event'. We can add an attribute 'txtconditions' containing a list of conditions like:

    TARGET-TASK= (workitem.budget && workitem.budget[0]>100)

With this information the WorkflowKernel now can evaluate the conditions of a 'Conditional-Event' to determine the next output Task/Event.

**Comment by rsoika** [comment]
parser does not break in example model.
So we can add the conditions from the gateway to the event....

**Comment by chrisw14** [comment]
Great!

> So we can add the conditions from the gateway to the event....

Didn't you mean from the event to the gateway?

And maybe the condition can only look like this?
`workitem.amount && workitem.amount > 100`
Without if, return and so on...

**Comment by rsoika** [comment]
Yes I think so, some refactoring is necessary but it looks good....

**Comment by rsoika** [comment]
@chrisw14  can you please verify the latest snapshot release 4.2.0-SNAPSHOT.

This version should work with conditional events. 
The important part in the WorkflowKernel is the new logic at line 418

**Comment by chrisw14** [comment]
Oh great, that was fast :-)

But if I use the format mentioned above (without if and return) I got the following exception. The same with your format with if and return:
```
Caused by: java.lang.NumberFormatException: For input string: "=3"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.imixs.workflow.WorkflowKernel.getNextTask(WorkflowKernel.java:425)
	at org.imixs.workflow.WorkflowKernel.processActivity(WorkflowKernel.java:345)
	at org.imixs.workflow.WorkflowKernel.process(WorkflowKernel.java:264)
```

Maybe it's only a small issue because the processid 3 would be the right process :-)

**Comment by rsoika** [comment]
Please take a look at this example model (it is part of the junit tests)

https://github.com/imixs/imixs-workflow/blob/master/imixs-workflow-core/src/test/resources/bpmn/conditional_event1.bpmn

a condition should look like this:

    (workitem._budget && workitem._budget[0]>100)

The expression is simply evaluated to an boolean.

**Comment by rsoika** [comment]
maybe you can share your model? It would be easier to discuss...

**Comment by rsoika** [comment]
You were right, I fixed this bug. Now it should work.

**Comment by rsoika** [comment]
I updated the docu too:

http://www.imixs.org/doc/modelling/howto.html

**Comment by chrisw14** [comment]
Great! It works fine, thank you very much!
