### ISSUE TITLE
Aborting a workitem without write access?

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#314]
Hi,
is it possible that a user with AUTHORACCESS which has no write access to a workitem cancels a workitem?
Normally the user should have only write access if he should write something. But the author or maybe someone else (e.g. his secretary) should have the possibility to cancel a workitem at every workflow step. 
Is it really necessary that all people who maybe want to abort the workitem has write access? Or is there another way?
I know it from another workflow system, there is a "agent" who cancels it with admin access if a user triggers that agent.
Which is the best way in imixs-workflow?

Second question: 
Is it possible to set general editors and readers to the model?
Or is it possible to give a group of users e.g. write permissions to all workitems of a specific model and not MANAGERACCESS to all workitems of all models?

And I think the table on http://www.imixs.org/doc/engine/acl.html is a bit wrong:
E.g. a user with AUTHORACCESS has read access to protected workitems (without having read or write permissions to this item) but not to his personal items?

Thank you!

**Comment by rsoika** [comment]
Hi,
you can give a user the EDITORACCESS if he should be able to write workitems in any situation.
A user with AUTHORACCESS who has not write access to a specific workitem should not be able to cancel/modify it!! What do you mean exactly with cancel? 

If you want a group of actors to be able to edit workitems of a specific model in any situation (we call them Process-Managers) you have to add these actors to the ACL - either by userid or by a application specific role.  

And off course you can give an agent MANAGEACCESS to update running process instances. This is exactly what the WorkflowSchedulerService does. 

Yes you are right, the ACL docu page looks a bit wrong...

**Comment by chrisw14** [comment]
Thanks for your ideas!

> What do you mean exactly with cancel?

E.g. if a user has created a workitem with wrong content, forwarded it already and now he want's to cancel ("abbrechen, stornieren") it and starting a new one. In this situation I don't like the idea of EDITORACCESS because then I can't know if the user may edit the document or only cancel it. I will have a look at WorkflowSchedulerService.

In which situations does a user actually have write access?
- If a user has MANAGERACCESS
- If a user has EDITORACCESS and is contained in the list $readaccess
- If the user is contained in the list $writeaccess
- If $isAuthor is true
- Something else?
Or checks $isauthor all of this?

> If you want a group of actors to be able to edit workitems of a specific model in any situation (we call them Process-Managers) you have to add these actors to the ACL - either by userid or by a application specific role.

But then you have to activate the checkboxes every time when you update the ACL, right? I was looking for a more generic solution.

**Comment by rsoika** [comment]
.... than keep things simple: 
If the creator of a request need be able to cancel the request even after the request was forwarded (e.g. for approval) than this is part of the process requirement and should equally be designed in the process model. The creator should keep its author access. 

I know international enterprises where a Holiday Request is exactly designed in this way. The requester can cancel its own Holiday Request even after he had forwarded it to his boss. 
To avoid that the requester is able to approve his own request, you can make use of the "Restrict To"-Feature of the Event in the modeler. You can set an ACL for the Event too. So you can avoid that the creator can see (and trigger) the 'approve' event. 

See 'visibility' : http://www.imixs.org/doc/modelling/activities.html#Workflow_Properties

**Comment by rsoika** [comment]
and yes, $isauthor checks all the rules for the author access.

**Comment by chrisw14** [comment]
Great!


> If you want a group of actors to be able to edit workitems of a specific model in any situation (we call them Process-Managers) you have to add these actors to the ACL - either by userid or by a application specific role.

But then you have to activate the checkboxes every time when you update the ACL, right? I was looking for a more generic solution.

I tried out the solution with the agent. It works fine but why is
`workflowService.getUserName();` always a empty string?
The WorkflowService is injected with EJB:
```
	@EJB
	WorkflowService workflowService;
```

**Comment by rsoika** [comment]
>But then you have to activate the checkboxes every time when you update the ACL, right?

yes 

>It works fine but why is workflowService.getUserName(); always a empty string?

This is an deployment issue. getUserName() simply returns the principal form the EJB context object. So make sure you agent is running in the right context (@runas...).

**Comment by chrisw14** [comment]
Okay then. 

Asking the other way around with the rights: Is there a method which gives me a list of users who have the mentioned $isAuthors rights for a specific workitem?

Thank you!

**Comment by rsoika** [comment]
no
