### ISSUE TITLE
Starting subprocesses?

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#315]
Hi,
I have the following model with subprocesses:
![subprozesse](https://user-images.githubusercontent.com/29482633/31174293-4ce92804-a90b-11e7-99e3-ce57f89ee0d0.png)

I expected that I can set a property for the model version in the properties of the sub process which will create a workitem of this model if I am in the task "Warten auf Subprozesse" but nothing happens. 
And I can't find such an option. So how can I start a sub process?

I only found this for subprocesses: http://www.imixs.org/doc/engine/plugins/splitandjoinplugin.html

Thank you!

**Comment by rsoika** [comment]
The BPMN Element "SubProcess" is currently not supported by the Imixs-BPMN Parser. 

The SplitAndJoinPlugin (http://www.imixs.org/doc/engine/plugins/splitandjoinplugin.html) is a solution to get more controll over some kind of 'Split & Join' Situation. But here you have no BPMN parallel gateway. 
The SplitAndJoinPlugin can be used to start a complete new workflow - even in a different model!
For example if you have a "purchase process", this workflow can start a "invoice process". But this is no parallel process flow as defined by BPMN 2.0. It is used to create new Process Instances - which we call 'subprocess'

You can also take a look at the feature "Split Events": http://www.imixs.org/doc/modelling/howto.html#Split_Events
This create new versions of a running process instance (a Split). But Imixs-Workflow is not supporting "joins" for different reasons as explained in the docu.

**Comment by chrisw14** [comment]
Hi Ralph,
this works for me fine. Thank you.
But I would have some further questions to the SplitAndJoinPlugin:

1. If I want to start a process with the first task after a start event, I tried it like this:
```
    <processid>1</processid>
    <activityid>1</activityid>
```
Then a exception will be thrown because the activityid 1 is not found. Which id has the start event? Can't find a property in the property menu of the bpmn model.

2. To copy some attributes I'm using the items attribute like this:
`    <items>type, ...</items>`
Can I set the current date / time like that too?

Thank you!
Chris

**Comment by rsoika** [comment]
In case that you want to imitatively start a process the start element hast be followed by an initial event:
 
![image](https://user-images.githubusercontent.com/1339124/34964313-43d1281e-fa4d-11e7-8adb-582a1a4eda01.png)

The BPMN Start Element is no Imixs-Element and is so only used to visualize the process start. The Initial Imixs-Event has to have a valid ID to be called in your first process step. It is true, that it would be nice to have a function in the ModelService which is resolving this ID automatically. But the problem here is, that you can potential have more than one initial events to start a process:
![image](https://user-images.githubusercontent.com/1339124/34964461-e718770c-fa4d-11e7-8180-9a85a373a5b1.png)

So this is the reason why its hard to support this in a automated way (I think).

To your second question: setting a value is describe by the ResultPlugn:
http://www.imixs.org/doc/engine/plugins/resultplugin.html

This allows you to initialize item values. 
Yes I ask my self why we don't have a feature to set the current timestamp....? 
.... maybe we could extend the method 'evalWorkitemResult' f the Workflow Service in line 916......

**Comment by chrisw14** [comment]
Oh great!

> So this is the reason why its hard to support this in a automated way (I think).

I think the 'normal bpmn' would be to have two or more start events with event definitions / conditions. Or one default start event and other start events (with IDs) which can be started manually with the SplitAndJoinPlugin.
But of course it's possible with an additional imixs event too.

> To your second question: setting a value is describe by the ResultPlugn:
> http://www.imixs.org/doc/engine/plugins/resultplugin.html

But is it possible to compute a value e.g. a random number with a java method?

>  Yes I ask myself why we don't have a feature to set the current timestamp....?

Do you mean the $created item? Is it actually possible to set this attribute if the workitem gets initialized? At the moment the attribute is only set when processing the workitem I think.

**Comment by rsoika** [comment]
> But is it possible to compute a value e.g. a random number with a java method?

This is not possible with the result plugin.
But it is possible if you use the RulePlugin with a appropriate script. 

> Do you mean the $created item? Is it actually possible to set this attribute if the workitem gets initialized? At the moment the attribute is only set when processing the workitem I think.

yes I think with the items $created and $modified you can easily assign the current date/time to another item. 

`<item name="mydate"><itemvalue>$created</itemvalue></item>`

but I have not tested this

**Comment by chrisw14** [comment]
> yes I think with the items $created and $modified you can easily assign the current date/time to another item.

Oh sorry, what I meant was independent from the plugins. 
$created is set in the processing phase. But I think the right time would be when initializing the document with $processid, $activityid and so on...
Now the time of $created is equal to the time when processing the document the first time.

**Comment by rsoika** [comment]
The $created attribute is automatically initialized by the JPA object  `org.imixs.workflow.engine.jpa.Document`. 
Only if you save a new Document 

`documentService.save(ItemCollection) `

which is not yet persisted you can set a creation date manually. This is for example necessary in case when restoring backup data or if you create a workitem via the Rest API. Once a Document is persisted you can not change this time stamp.
