### ISSUE TITLE
Bug in ACL update mechanism after conditional gateway

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#327]
Hi Ralph,

using the processing lifecycle of imixs-workflow the following attributes are not set when processing from task 2 to task 3:

![model](https://user-images.githubusercontent.com/29482633/32145875-b470e7a0-bccf-11e7-8d6e-dc5f6f909f40.png)

namownershipnames -> namowner
namaddreadaccess -> $readaccess
namaddwriteaccess  -> $writeaccess

With the following model it works fine:
![workflow_works](https://user-images.githubusercontent.com/29482633/32221265-2ad2d4e2-be35-11e7-8640-f6d1371bd003.png)

Where is the bug?

Thank you!

**Comment by rsoika** [comment]
I will look into this.

**Comment by rsoika** [comment]
Hi Chris,
thank you for this finding! It was indeed a critical bug not detected by the current junit tests. 
I fixed it now. 
Can you please test the latest snapshot release to confirm that this is working for our. 

There is now a new method available :

`    workflowService.evalNextTask(workitem,event);`

**Comment by chrisw14** [comment]
Hi Ralph,
thank you very much for fixing it so quickly. I tried it out and now it worked for my model.
Very good, the new method is a good idea. Thank you!
Chris
