### ISSUE TITLE
Read out name of bpmn model

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#328]
Hi Ralph,
is it possible to read out the name of a bpmn model?
It's set here:
![image](https://user-images.githubusercontent.com/29482633/32283388-78f719b8-bf24-11e7-84d9-5ef6eb0cfb2d.png)

But I can't find it in the migration:
https://github.com/imixs/imixs-workflow/blob/master/imixs-workflow-core/src/test/java/org/imixs/workflow/bpmn/MigrateImixsModelToBPMN.java

The workflowgroup is sometimes a curious name which I can't change without replacing it in the source code of the bpmn file.
The txtname of a model is always "[environment.profile]". What does this mean?

Thank you!

**Comment by rsoika** [comment]
It is always the name of the BPMN process (tab process) - not the name of the diagram itself (tab general). 
Note: A collaboration diagram can contain more than one workflows. 
So in your case you need to select to pool element to edit the name.

**Comment by chrisw14** [comment]
Okay, thanks! It is a bit confusing with three name attributes in general, process and definition, but okay.

**Comment by chrisw14** [comment]
Hi Ralph, 
further question to this: How can I define who (which groups or users) can start a process? 
And how can I read out these attributes set in the model?
![image](https://user-images.githubusercontent.com/29482633/33234183-7ad91f90-d222-11e7-9c33-d31d679f0d71.png)
Is there a general way to find out the name of the attributes?

Thank you!

Cheers
Chris

**Comment by rsoika** [comment]
The Imixs-Workflow engine dose not restrict the creation of a new process instance by model name or user groups. This need to be implemented as part of your application. 

The ModelService provides you a way to get the full BPMN file representing your model:

```
ItemCollection modelEntity=modelService.loadModelEntity(modelversion);
List<?> fileData=modelEntity.getFile(modelversion + ".bpmn");
byte[] file=fileData[1];
// parse bpmn file...
```

But so far we did not provide a parser for the full bpmn file. You need to parse the file by yourself.
