### ISSUE TITLE
Most of the links on tutorial doesn't work

### ISSUE THREAD

**Issue by 4asifm** [imixs/imixs-workflow#431]
On this tutorial
https://blog.imixs.org/2014/09/10/building-web-application-imixs-workflow-part/
most of the links doesn't work.

Is there any other tutorial?

**Comment by rsoika** [comment]
ups - yes we need to fix this.
But you can take a look here:  https://imixs.org/doc/sampleapplication.html
This is the JSF Example.

You can also take a look at the new MVC example applciation: https://github.com/imixs/imixs-mvc-example

**Comment by rsoika** [comment]
I fixed the links and also added a new updated tutorial:
https://blog.imixs.org/2018/10/21/tutorial-imixs-workflow-and-jakarta-ee/
