### ISSUE TITLE
i am  trying to install imixs plugin on eclipse  Neon.3 but got that error

### ISSUE THREAD

**Issue by engahmedtahaa** [imixs/imixs-workflow#468]
i am  trying to install imixs plugin on eclipse  Neon.3 but got that error

Unable to read repository at http://www.imixs.org/org.imixs.eclipse.bpmn2.updatesite_neon/content.xml.

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:554)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:435)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:216)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.layerProtocol(ManagedClientConnectionImpl.java:394)
	at org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:814)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:615)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at urity.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)

**Comment by rsoika** [comment]
We are currently developing against Eclipse Oxygen. So I am not aware about the situation with Eclipse Neon for the moment. Did you succeed to install first Eclipse BPMN-2 Plugin. 
The Update-Site URL for Eclipse Neion is:  http://download.eclipse.org/bpmn2-modeler/updates/neon/1.3.0

I think Imixs-BPMN shout run with this plugin too. Can you test this?

**Comment by engahmedtahaa** [comment]
Thanks rsoika 

 i have install BPMN-2 Plugin but i don't know if it direct from imxs or not, when i hit this url on browser i got  403
https://www.imixs.org/org.imixs.eclipse.bpmn2.updatesite/

**Comment by rsoika** [comment]
Yes this is normal. The Update site is not a visual website and only used for Eclipse Update site (in the Eclipse Install) dialog. 
![image](https://user-images.githubusercontent.com/1339124/51530009-4836d400-1e3a-11e9-9f86-c0060e881a96.png)

**Comment by engahmedtahaa** [comment]
yes i face the same issue on the eclipse 

![image](https://user-images.githubusercontent.com/22871674/51532450-2d238e80-1e51-11e9-9de8-9943bf4f0fd5.png)

**Comment by rsoika** [comment]
Ok than let's try the following url for Eclipse Neon:

https://www.imixs.org/org.imixs.eclipse.bpmn2.updatesite_neon

**Comment by rsoika** [comment]
You can also take a look [here](https://www.imixs.org/doc/modelling/install.html) for more information about older versions of Eclipse.

**Comment by engahmedtahaa** [comment]
the same issue with
https://www.imixs.org/org.imixs.eclipse.bpmn2.updatesite_neon

i think this issued related to the certificate with JDK

**Comment by engahmedtahaa** [comment]
if I use BPMN as an alternative for imixbpmn it will suitable or not

**Comment by rsoika** [comment]
Yes you are right this is a JDK certificate problem. What java version are you using? Can you use JDK 8 or higher on your machine?

Have you seen these discussions: 
* https://stackoverflow.com/questions/38844061/pkix-path-building-failed-in-eclipse
* https://www.eclipse.org/forums/index.php/t/1085851/
* https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find

Is there any reason why you need to run Eclipse Neon instead of actual Eclipse Photon? 


To work with Imixs-Workflow you need the Imixs-BPMN tool because this is generating the BPMN extensions which are holding a lot of processing instructions.

**Comment by engahmedtahaa** [comment]
Yes you are right this is a JDK certificate problem. What java version are you using? Can you use JDK 8 or higher on your machine?
yes I am current;y use 1.8 U 181 


Is there any reason why you need to run Eclipse Neon instead of actual Eclipse Photon?

no, I will install it and try again 

but how can I download the certificate file of imixs-bpmn site

**Comment by engahmedtahaa** [comment]
Is there any reason why you need to run Eclipse Neon instead of actual Eclipse Photon?

i have downloaded  it and the same issue still exists

**Comment by rsoika** [comment]
can you please post once again your current  error message / stacktrace.

**Comment by engahmedtahaa** [comment]
i trying to download the certificate and added it in my jdk stores but currently i go that error 

java.security.cert.CertificateException: No X509TrustManager implementation available

**Comment by engahmedtahaa** [comment]
regards to the error message on photon the same as Neon

**Comment by rsoika** [comment]
There is something strange going wrong with your JDK and the keystore. I do not think that the reason is eclipse or imixs-bpmn. If you search for the erroe message 'NO X509TrustManager' there is a lot of discussion on the internet. In the moment I do not know what to do in this situation. Can you test some other different mashine to sort this out?

**Comment by engahmedtahaa** [comment]
i have done this activity and trying in another machine the same issue appears and also trying to install another jdk and another eclipse version with no luck

i don't if the solution trying to use anther opensource bpm solution

**Comment by engahmedtahaa** [comment]
kindly can you send me the plugin as zip and i install it on side eclipse @rsoika

**Comment by rsoika** [comment]
Here you can download the latest plugin version as a zip file.

[org.imixs.eclipse.bpmn2.updatesite-1.4.8-SNAPSHOT.zip](https://github.com/imixs/imixs-workflow/files/2788258/org.imixs.eclipse.bpmn2.updatesite-1.4.8-SNAPSHOT.zip)

**Comment by engahmedtahaa** [comment]
Thanks a lot @rsoika I have fixed the issue it is related to https with my network proxy so it is a network issue as imixs CA not authorized or not known CA, so h hope to change the ssl provider.
Thanks again for your support. 

appreciate if you can send me good resources to start from it in imixs.

**Comment by rsoika** [comment]
There a several ways how you can use Imixs-Worklfow. Look [here](https://www.imixs.org/doc/index.html). Maybe the docker-way is the easiest for you.
