### ISSUE TITLE
ViewHandler / ViewController

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#484]
Hi,
just saw the last changes of ViewHandler and ViewController to introduce a cache.
One question to this topic:
Wouldn't it make sense to load all workitems with the query which was set, store the result view scoped and then iterate over this result with the ViewHandler (forward, back, setPage, setPageSize, sortBy, ...) without loading the workitems once more?
In my applications it takes much resources if i want to browse through some pages.
What are your thoughts about it?
Thank you.

**Comment by rsoika** [comment]
You mean loading all workitems into the viewscoped cache without paging? This is no good idea as the bean caches the complete result even if the user did not use forward/backward paging. 

The reason for the change was that before version 4.5 all results was cached in session scope. We run into memory problems when there were a lot of users logged in at the same time. This was the reason to reduce the data stored in a session scope. 

Please note that with the new implementation the view result is only request scoped. The ViewController stores only the query and the page index in the ViewScoped session. So we reduce the memory footprint of your application. 

Think about the behavior of a REST API - here you never have the chance to cache data. This makes the REST approach very efficient. JSF seduces the developer to store data into a session, which is generally a bad idea. 

After reading [this book](https://www.allitebooks.in/the-definitive-guide-to-jsf-in-java-ee-8/) I wrote some of the learning into my [blog](https://ralph.blog.imixs.com/2018/12/08/jsf-best-practice/)...

**Comment by chrisw14** [comment]
Okay, you're right. With my implementation idea the data could be old while browsing through the pages.

But I want to compute filter items for a existing view of all workitems. Therefore I have to load ALL workitems of the view, go through the list and take every value into my list which was not added before.
How can this be implemented without loading ALL workitems? As far as I know grouping is not possible with lucene, right?
Thanks!

**Comment by rsoika** [comment]
You need to filter your view result by a Lucene Query. This is the first and only valid approach. You can not load ALL workitems. This  is an anti-pattern. You should only load what your JSF page is showing.  And of course you can create very complex queries. See [here](https://www.imixs.org/doc/engine/queries.html). 

Just to make the use case more clear: if you have a process database with several thousand active process instances.  How would you deal with such a data set in the backend? You can not load all data into the heap space.

**Comment by chrisw14** [comment]
Yeah, of course I filter my view result. With "ALL workitems" i mean all workitems of the current view, but not only the items of the current page. But how do I find out e.g. all possible $workflowgroups of the current view? Is there an better way to iterate over ALL workitems (of the current view)?

**Comment by rsoika** [comment]
There is a grouping feature in lucene:
https://lucene.apache.org/core/6_5_1/grouping/org/apache/lucene/search/grouping/package-summary.html#package.description

another solution is to lookup all groups from the model service 

```
public List<String> getWorkflowGroups() {

		Set<String> set = new HashSet<String>();
		List<String> versions = modelService.getVersions();
		for (String version : versions) {
			try {
				set.addAll(modelService.getModel(version).getGroups());
			} catch (ModelException e) {
				e.printStackTrace();
			}
		}
		List<String> result = new ArrayList<>();
		
		for (String agroup : set) {
			if (result.contains(agroup))
				continue;			
			result.add(agroup);
		}
		Collections.sort(result);
		return result;
	}
```

But this will not guarantee the workitems exist for each group.
