### ISSUE TITLE
Overriding WorkflowKernel's generateUniqueID()

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#485]
Is it possible to override the generateUniqueID() of the WorkflowKernel with another format?
At the moment, I cannot do it with @Override:
![grafik](https://user-images.githubusercontent.com/29482633/53694286-faa07600-3dac-11e9-8da5-0cc3a1c9c36b.png)

Is there another way I can define my own format?
Thank you.

**Comment by rsoika** [comment]
I have never think about this. 
Why would you like to overwrite it? It is important to have a unique identifier and the UUID class is the perfect fit.

**Comment by chrisw14** [comment]
I would like to add the initials of the requester and take similar IDs for subprocesses, maybe use ongoing numbers instead of such long identifiers.

**Comment by rsoika** [comment]
The UID is used by different components inside Imixs-Workflow. E.g. by the Rest API identifies UID requests by the specific pattern. Also the Imixs-Archive project is bound tight to the UID. 

I think the correct solution is to create your own custom UID and add it to your workitem. You can implement an Observer Pattern an react to the [_DocumentEvent : ON_DOCUMENT_SAVE_](https://www.imixs.org/doc/engine/documentservice.html). In this custom EJB you can also implement your custom finder methods you need. 
The CDI DocumentEvent guaranties that your custom ID is set correctly to any document.
