### ISSUE TITLE
Using in oracle apex

### ISSUE THREAD

**Issue by j209** [imixs/imixs-workflow#500]
Hi
Can we useimixs-workflow in oracle apex?

**Comment by rsoika** [comment]
You can run Imixs-Workflow as a microservice and this fits perfectly into the architecture for Oracle APEX.

The Imixs-Worflow can either send data into the APEX platform by the Rest API defined by APEX or you can call the Imixs-Worklfow to create or udpate a process instance via the Imixs Rest API.

If you are looking for support you can contact us [here](https://www.imixs.com/contact/)
