### ISSUE TITLE
OwnerPlugin - rename "namOwner" into "$owner"

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-workflow#530]
Introduce the new Item name "$owner" instead of "namOwner" to align the internal item to the $writeAccess and $readAccess

**Comment by chrisw14** [comment]
Ralph, can there be also a field like $ownerNameList which contains all usernames of $owner if $owner contains groups? Therefore the group needs to be resolved into usernames.

**Comment by rsoika** [comment]
This is a application specific requirement. We can not add such a specific code into the workflowService because the WorkflowService is not aware of users or groups. It just deals with Strings. I think such a feature need to be resolved by a Plug-In which is the perfect place.
