### ISSUE TITLE
Rename "txtworkflowhistory" into $workflowlog

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#532]
Can the important field "txtworkflowhistory" also be renamed e.g. into $workflowlog or $workflowhistory? Maybe it should also be added to the workflow engine instead of a plugin because it's a part of processing workitems.

**Comment by rsoika** [comment]
I am not sure if it is a good idea to move this code into the WorkflowService. The workflow history is something which need to be customizable by an application. So a Plug-In is fine and can be replaced easily by individual requirements. 

We use the prefix '$' only for internal items controlled by either the WorkflowKernel or the WorkflowService. 
But you are right the naming of this field is terrible. The name has historical reason.

**Comment by chrisw14** [comment]
Okay, right. Then I also can rename it by my own in the plugin.

**Comment by chrisw14** [comment]
How can I switch the content of the field "txtworkflowhistory" to the new field $workflowlog for ALL workitems? I thought this would be possible with imixs-admin but it's only possible with hard coded values?

In Java I tried this:
```
			if (!item.hasItem("$workflowLog")) {
				item.replaceItemValue("$workflowLog", item.getItemListArray().get("txtworkflowhistory"));
			}
```

**Comment by rsoika** [comment]
yes currently it is only possible with static values. The Admin-Client did yet provide a feature to copy the content form one field into another.

**Comment by rsoika** [comment]
You can implement an AdminP-Job to update data in your workflow instance. 
See: https://www.imixs.org/doc/engine/adminp.html

Code Example here:

https://github.com/imixs/imixs-workflow/blob/master/imixs-workflow-engine/src/main/java/org/imixs/workflow/engine/adminp/JobHandlerUpgradeWorkitems.java
