### ISSUE TITLE
Unable to connect to repository http://www.imixs.org/org.imixs.eclipse.updatesite/content.xml

### ISSUE THREAD

**Issue by SaptefratiA** [imixs/imixs-workflow#57]
Unable to connect to repository http://www.imixs.org/org.imixs.eclipse.updatesite/content.xml
Unable to connect to repository http://www.imixs.org/org.imixs.eclipse.updatesite/content.xml
Connection to http://www.imixs.org refused

**Comment by rsoika** [comment]
closed
