### ISSUE TITLE
Run the workflow modeler as standalone application without having to open the Eclipse IDE to model a workflow

### ISSUE THREAD

**Issue by omarAjmi** [imixs/imixs-workflow#586]
Hi, i have a great intrest in this project and i've spent the last week reading you documenttion and your source code, and i had this idea of **runnig the Workflow modeler as a standalone application** without the need to **run eclipse IDE**, so it interacts with Imixs-engine through the **REST API** or whichever suitable mechanism.
So my question **is this doable** with the current version or not, and if yes what are the guidelines that iu have to follow to make it work.
[the camunda eclipse modeler](https://github.com/camunda/camunda-eclipse-standalone) is an example of what i am talking about.

**Comment by rsoika** [comment]
I am not sure if I understand you question correctly. Imixs-Worklow, as you may have seen, also has a [Rest API](https://www.imixs.org/doc/restapi/index.html). So you can of course access a running workflow instance though this api. This includes the model management.

The Eclipse IDE is used to design a BPMN2 model with the Imixs-BPMN Plugin which is based on the Eclipse BPMN2 Plugin. 
You need the Imxis-BPMN Plugin only to design your model. You do not need to run the Eclipse IDE to create or update process instances.

As Imixs-BPMN is in its core a normal plug-in you can also create an Eclipse Application including this plugin. This is a feature of Eclipse itself. If you go this way, you can start an instance of Eclipse only providing the Imixs-BPMN Plugin.
Or you can add additional functionality (e.g. a Business Process Management Suite) into you Eclipse App. Your Eclipse app communicates with the Imixs-Workflow instance via the Imxis Rest API. See also here: https://www.vogella.com/tutorials/EclipseRCP/article.html

To simplify the way to launch an Imixs-Workflow instance you may take a look at the [Imixs-Microservice project](https://github.com/imixs/imixs-microservice). This project allows you to start an Imixs-Workflow server out of the box as a Docker Container. 

I hope this helps answering your question?

**Comment by omarAjmi** [comment]
@rsoika yeah, i meant only the eclipse IDE graphical modeler that enables you to design the workflow.

**Comment by rsoika** [comment]
Currently it is a Plugin "only" .
I know that you can build an Eclipse RPC from it, but I do now know how. 
So - yes it is possible!

**Comment by omarAjmi** [comment]
thank you
