### ISSUE TITLE
Task properties do not match documentation in diagram designer

### ISSUE THREAD

**Issue by lennycode** [imixs/imixs-workflow#594]
I believe I am using the latest version. 
The documentation has a different icon on the Task (None of the tasks in the palette have it)
Also, the last tabs, Task, I/O parameters, are different from Workflow, Application

![image](https://user-images.githubusercontent.com/845855/67154879-1ff8da80-f2d1-11e9-8dca-37e9111a1f9e.png)

**Comment by lennycode** [comment]
I believe now that Tasks have to be chosen from Imixs-Workflow Panel. I don't know how the other "Tasks" interact with the system, or if they should be ignored.

**Comment by rsoika** [comment]
Yes you are right. Those Elements related to Imixs-Workflow have to be chosen form the Imixs Panel:

![image](https://user-images.githubusercontent.com/1339124/67157149-84935400-f328-11e9-83e8-fb67dcff3b2d.png)

But you can combine these elements with any other BPMN elements. The Imixs-Workflow engine ignores them. But the standard BPMN elements are often needed for a better documentation of your process.

**Comment by lennycode** [comment]
Thanks!
