### ISSUE TITLE
Where do I find the imixs-workflow-index-lucene jar?

### ISSUE THREAD

**Issue by lennycode** [imixs/imixs-workflow#596]
**imixs-workflow-index-lucene**

This is not coming up in Maven.

![image](https://user-images.githubusercontent.com/845855/67214320-8ffc8300-f3ed-11e9-862c-3ce30b10416f.png)

**Comment by rsoika** [comment]
Yes, this is still a snapshot release.
You can add the maven central snapshot repository to your maven pom.xml:


	
	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>

Either way, we'll release 5.1.0 in this week

**Comment by rsoika** [comment]
Version 5.1.0 is now released - will take some hours until it will be reloaded by maven central...
