### ISSUE TITLE
Why am I receiving this error?

### ISSUE THREAD

**Issue by lennycode** [imixs/imixs-workflow#597]
I cloned the sample app, then built the project in Maven  
I added the Derby DB, and the security profile
I then tried to deploy in Payara: (using the .WAR file)

Error occurred during deployment: JNDI lookup failed for the resource: Name: [java:module/env/org.imixs.workflow.engine.plugins.MailPlugin/mailSession], Lookup: [mail/org.imixs.workflow.mail], Type: [javax.mail.Session]. Please see server.log for more details.
--

**Comment by rsoika** [comment]
You can add the following vm-option to suppress this deployment issue in payara/glassfish

    <jvm-options>-Ddeployment.resource.validation=false</jvm-options>

I guess you have not yet added a mail resource into your server setup?
Under resources in your domain.xml file add:

      <mail-resource auth="false" host="localhost" from="info@foo.com" user="admin" jndi-name="mail/org.imixs.workflow.mail"></mail-resource>

If you take a look into the directory /src/docker/configuration/payara/ you will find a running setup for a domain.xml file

**Comment by lennycode** [comment]
Thanks! Also had this issue in docker: (had to reboot server)
![image](https://user-images.githubusercontent.com/845855/67291447-8b000800-f4af-11e9-82e4-3d1512bd6b9c.png)
