### ISSUE TITLE
Entity Service?

### ISSUE THREAD

**Issue by lennycode** [imixs/imixs-workflow#598]
I found that feature in an older version of the API. 

Is the equivalent still available?
(For example, I would like to add users on the fly)

Thanks.

**Comment by rsoika** [comment]
The entity service was replaced with full feature update by the document service. This service can be used to create or manage data objects (e.g. user objects, configuration objects, ..) independent from the workflow process instances. 

https://www.imixs.org/doc/engine/documentservice.html

Does this answer your question?

**Comment by lennycode** [comment]
Yes, I noticed it in the API section as well. 
Could you give a quick example to add a User (and team) using the API? (like in the sample app).
Thanks

**Comment by rsoika** [comment]
If you want to use the Rest API you can do something like this:

    curl --user admin:adminadmin -H "Content-Type: application/json" -H 'Accept: application/json' -d \
       '{"item":[ \
                 {"name":"type","value":{"@type":"xs:string","$":"user"}}, \
                 {"name":"name","value":{"@type":"xs:string","$":"melman"}}, \
                 {"name":"email","value":{"@type":"xs:string","$":"melman@foo.com"}}, \
                 {"name":"display_name","value":{"@type":"xs:string","$":"M. Melman"}}\
         ]}' \
         http://localhost:8080/api/documents/

**Comment by rsoika** [comment]
... and you can search for it with a GET resource like this:

    /api/documents/search/type:"user"

**Comment by lennycode** [comment]
I tried the above query in Postman and Curl.
I get:
**HTTP Status 415 - Unsupported Media Type**

My headers are correct.

**Comment by rsoika** [comment]
did the curl command work for your?
