### ISSUE TITLE
ValidationError with RulePlugin

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#603]
I get the following error using the RulePlugin:
```
12:34:20,932 SEVERE [org.imixs.workflow.WorkflowKernel] (default task-100) Plugin-Error at org.imixs.workflow.engine.plugins.RulePlugin: VALIDATION_ERROR (BusinessRule: validation failed - ErrorCode=VALIDATION_ERROR)
12:34:20,933 SEVERE [org.imixs.workflow.engine.WorkflowService] (default task-100) processing workitem 'D008499465704F1188E9B2C9DFDD5B48 failed, rollback transaction...
12:34:20,940 WARNING [org.imixs.workflow.faces.util.ErrorHandler] (default task-100) ErrorHandler: Can't find bundle for base name bundle.app, locale de_DE
12:34:20,940 WARNING [org.imixs.workflow.faces.util.ErrorHandler] (default task-100) ErrorHandler cauth PluginException - error code=VALIDATION_ERROR - BusinessRule: validation failed - ErrorCode=VALIDATION_ERROR
12:34:20,944 SEVERE [workflow.WorkflowDocument] (default task-100) Processing not successful - taskID is still the same
```

My rule looks like this:
```
var result = {};

if (workitem.approvalnote == null || workitem.approvalnote[0] == "") {
	result.isValid = false;
	result.errorMessage = '<p><b>Möchten Sie diese Anforderung wirklich abbrechen?</b></p>' +
		'<p>Bitte geben Sie eine Begründung an:</p>';
}
```

Can you please tell me what's the problem is? Thank you.

**Comment by rsoika** [comment]
The rule checks the value of the item "approvalnote". If it's empty the validation exception is thrown as shown by your log messages. 

What behavior did you expect?

**Comment by chrisw14** [comment]
I try to catch the PluginException like that:

```
try {
			super.setWorkitem(workitem);
			super.process();
		} catch (WorkflowException e) {
			logger.severe("WorkflowException");
                }
```

Why doesn't the console show the "WorkflowException" text?
I only get the errors posted in the first post and my application doesn't anything...

**Comment by rsoika** [comment]
The org.imixs.workflow.faces.data.WorkflowController does completely handle WorklfowExceptions and adds a corresponding message into the Message List of the FacesContext

     FacesContext.getCurrentInstance().getMessageList();

This is why you got no exception here. The goal of the WorkflowController is to provide the front-end with a useful message text in such situations. 

If you want to handle Exceptions by yourself, than you should implement a custom processing method.  

See here: https://github.com/imixs/imixs-workflow/blob/18b6ff1e690279a44a07bec8fafd39af6516cc87/imixs-workflow-faces/src/main/java/org/imixs/workflow/faces/data/WorkflowController.java#L367

**Comment by rsoika** [comment]
... But there should no need for your application to handle PluginExceptions.
