### ISSUE TITLE
Workflow Actor Properties

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#604]
I always used for actors in the BPMN model the following definition:

![grafik](https://user-images.githubusercontent.com/29482633/68543524-674a2680-03b8-11ea-9e1f-bab06e500d29.png)

This means: The role with name "Chef" is saved in the item "chef" and the user can select his boss of the group "ALL_CHEFS". This is not possible anymore. Is it possible to allow this definition again?
At the moment, I don't know where should I define it if not here in the model. Thank you.

**Comment by rsoika** [comment]
I did not understand what you mean. I do not think that we ever supported the convention 

    label | field | group

Take a look here: https://www.imixs.org/doc/modelling/main_editor.html#The_Actor_Properties

You can either map the actor to a named item stored in the workitem or a fixed username list

**Comment by chrisw14** [comment]
Okay, I'll implement the group with an additional workitem / field.
