### ISSUE TITLE
/documents/search/ - get object count

### ISSUE THREAD

**Issue by ozzi-** [imixs/imixs-workflow#645]
**Is your question related to a problem? Please describe.**
I have a query like the following:
```
workflow/rest-service/documents/search/(type:"workitem")
```
The result contains a field called "docref" which seems to be a list of objects.
When using the HTML render of the result, it is a string as such "item1\~item2\~item3".
The JSON output looks like the following:
```
{"item":[{"value":["item1","item2","item3"],"name":"docref"}]}]}
```

How can I do a search query that only returns results that have 1 or more items in said field?
I tried using regexp such as:
```
workflow/rest-service/documents/search/(type:"workitem")&&(docref:/.*~.*{1,}/)
```
but that does not work.
Neither did my attempts using COUNT and jqpl (inspired by #26):
```
workflow/rest-service/documents/jpql/SELECT COUNT(document.docref) FROM Document document
```

If you can point me in the right direction, I would be very happy.

Cheers

**Comment by rsoika** [comment]
This is a lucene specific topic. 

First take a look at the schema definition used by Imixs-Wokfllow [here](https://www.imixs.org/doc/engine/luceneservice.html).
Your item 'docref' is a custom field related to your application and is not automatically indexed by the indexer. To add the item you need to extend your index schema definition.

It sounds like docref is a technical field, so you should add the field to the property 'index.fields.noanalyze'

     index.fields.noanalyze=docref

Add or edit your imixs.properties file.

After extending the schema you need to re-index your imixs document/workitem. A  process or save on related document will do this.

Now your docref items values will be indexed. You can use a Lucene Query to find the interesting documents/workitems:

     (type:"workitem") AND (docref:*)

This should do it. 

Let me know if this works for you.

**Comment by rsoika** [comment]
If you just want to count the documents you can use the method 'count' instead of 'find'.
See [here](https://www.imixs.org/doc/engine/documentservice.html#Count_Total_Hits), But the search term is the same.

**Comment by ozzi-** [comment]
Hi @rsoika  
Thanks so much for the fast response, good point on adding it to the index, that must have been the problem. Ill get going then ;)
