### ISSUE TITLE
Question on Modeling the workflow

### ISSUE THREAD

**Issue by yogeshkodei** [imixs/imixs-workflow#668]
Requirement:
Role X  finds a problem on am artefact and wants to create a problem report. 

Once the Problem report is created it has to be assigned to somebody before it can be reviewed. There are also certain other properties or attributes like estimated date of fix to be made available. So the need to have someone assigned to the problem report or filling any required attribute are a must. Note that the assignee can be automatically assigned or manually assigned. 

Once the Problem has been analyzed properly and triaged, let us say in this case it is a change to the current requirements. So a Change Request needs to be created. This change request should be related to the artefact that was on the problem report and before it moves to the next state. Once the CR is related to the artefact other objects like a Change Task get created behind the scenes. Before the CR can be moved along the Change Task should be assessed in terms of impact analysis, assigned to a person for the task etc. 

I could go on with the entire process. But just wanted to see if the tool can be used and if affirmative how would I model the required fields, connections etc at the Task level?

**Comment by rsoika** [comment]
yes - Imixs-Workflow is designed for exactly this kind of requirements.

If you take a look into the [Imixs-JSF-Example](https://github.com/imixs/imixs-jsf-example) you will get a good first impression how this can look like.

Your application is responsible to create a new process instance and assign all necessary data to it. 
To create a second process on a running process instance you can design a second model (change request) and use the [SplitAndJoin Plugin](https://www.imixs.org/doc/engine/plugins/splitandjoinplugin.html) to create the second process. Both process instances are connected to each other and can trigger events out from there own process model.

**Comment by yogeshkodei** [comment]
Thank you. Where would I specify which attributes and which relationships are required? Is it part of the submit event or is it part of the activity?
 
--------- Original Message --------- Subject: Re: [imixs/imixs-workflow] Question on Modeling the workflow (#668)

**Comment by rsoika** [comment]
A process instance is a special type of business object. You can assign any business data to a process instance you need. I can't tell you which data is required for your business request. The SplitAndJoin Plugin allows you to copy business data from the origin process instance to the sub process instance. For example an ticket-id or something else. But it's up to you to design your business process.

**Comment by yogeshkodei** [comment]
Greetings:
Sorry I might be asking several basic questions.
 
There are several fields on an event or Task. Can I specify what is required in those fields or does it have to be modeled elsewhere?
 
Yogesh
 
--------- Original Message --------- Subject: Re: [imixs/imixs-workflow] Question on Modeling the workflow (#668)

**Comment by rsoika** [comment]
You can find a list of all items managed by imixs-workflow [here](https://www.imixs.org/doc/quickstart/workitem.html). All other items are defined and managed by your application. 

If you want to validate application specific data items from your model, you can use the [RulePlugin](https://www.imixs.org/doc/engine/plugins/ruleplugin.html).
