### ISSUE TITLE
Task details response doesnt come as a json

### ISSUE THREAD

**Issue by guilhermemauro** [imixs/imixs-workflow#715]
Hi there! A Pythonic guy here.
I'm studying a possibility to use imixs as service in my Python project using REST. My questions is about json response: 
I'm trying to get task details as json, but it seems not working, as you can see:

![image](https://user-images.githubusercontent.com/12633498/99888187-93ce8a80-2c29-11eb-97eb-a83cbcbf75e6.png)

This is a bug or a expected behavior? And, how can I fix this? Thanks!

**Comment by rsoika** [comment]
Yes, this is true. The query param "format" is not recognized by the modelSevice.

But JSON is supported. You need just to send the corresponding header:

    Accept:application/json

I hope this will help you. In any case I will accept your request as a feature request. All interfaces should behave the same way.

**Comment by guilhermemauro** [comment]
Thanks @rsoika!
